FROM node:20-alpine

WORKDIR /app

COPY package*.json .
RUN npm install

COPY jest.config.ts .
COPY tsconfig.json .
COPY nodemon.json .
COPY src ./src
COPY tests ./tests

# CMD ["npm", "run", "test"]
