# Dockerfile.ci
FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy TypeScript & Jest configs
COPY tsconfig.json jest.config.ts ./

# Copy source code and tests
COPY src ./src
COPY tests ./tests

RUN npm i ts-node
# Run tests using tsx
CMD ["npm", "run", "test"]
